import { PROJECTS_CONTENT } from "./content";

const CASE_STUDY_TRANSLATIONS = {
  es: {
    "ti-nspire-cxii-custom-keyboard-remap": { facts: [["Dispositivo", "TI-Nspire CX II CAS"], ["Objetivo", "OS 6.2.0.333 con Ndless"], ["Alcance", "Solo eventos de teclas alfabéticas"]], sections: [["Reasignar la entrada alfabética a QWERTY", "La disposición alfabética original de la calculadora resulta lenta para quien escribe por memoria muscular con QWERTY. El remapeo conserva el hardware y cambia únicamente la letra que llega al campo de entrada, por lo que el resto del teclado sigue siendo familiar."], ["Modificar solo los eventos de letras en la cola del sistema", "La aplicación instala un hook residente en la cola de eventos del sistema operativo. Examina los eventos A-Z y a-z, sustituye el byte ASCII mediante una pequeña tabla y deja intactos los modificadores, las teclas no alfabéticas y los demás datos del evento."], ["Limitar la instalación a OS 6.2.0.333", "No es un parche universal: la versión actual se ha creado y probado para la CX II CAS con OS 6.2.0.333. Un modo de comprobación muestra el mapeo antes de instalar el hook."]]},
    "macro-recorder-plus": { facts: [["Plataforma", "Escritorio Windows"], ["Flujo", "Grabar, editar, reproducir y exportar"], ["Exportaciones", "Script Python o EXE opcional"]], sections: [["Convertir grabaciones en acciones editables", "Los eventos de ratón y teclado sin procesar rara vez constituyen una automatización terminada. Macro Recorder Plus los convierte en una tabla de acciones que se pueden activar, etiquetar, reordenar y editar, además de permitir pasos manuales."], ["Exportar flujos como scripts de Python o ejecutables", "Cada flujo puede exportarse con sus dependencias, recursos, lanzador y notas de ejecución. Si resulta más práctico entregar un solo archivo, el mismo flujo puede generar un ejecutable de Windows mediante PyInstaller."], ["Mantener las credenciales fuera de los archivos de macro", "Las acciones secretas guardan el nombre de una variable de entorno, nunca la contraseña. De este modo las macros compartidas o archivadas no exponen credenciales."]]},
    calendar: { facts: [["Interfaz", "Aplicación de una sola página en React"], ["Tarea", "Planificación escolar recurrente"], ["Integración", "Eventos de Google Calendar"]], sections: [["Organizar una semana escolar recurrente", "Los horarios escolares se repiten, pero las pruebas y los deberes cambian continuamente. Homework Calendar reúne clases, evaluaciones y tareas en un flujo breve para que la planificación semanal no tenga que rehacerse desde cero."], ["Convertir clases y tareas en eventos de calendario", "La interfaz permite elegir el tipo de evento, la materia y la fecha antes de enviarlo a Google Calendar. Las clases recurrentes quedan separadas de los recordatorios puntuales, de modo que la agenda sigue siendo clara."], ["Diseñar para el uso cotidiano", "La aplicación prioriza pasos directos y datos visibles sobre pantallas de configuración extensas. La conexión con Google se configura una vez y las preferencias pueden conservarse para sesiones posteriores."]]},
    "handwriting-pipeline": { facts: [["Proyecto base", "My Text in Your Handwriting"], ["Tipo de proyecto", "Extensión de flujo y herramientas de escritorio"], ["Uso", "Personal, educativo y de investigación"]], sections: [["Preparar muestras y texto para la síntesis", "Las muestras escaneadas necesitan limpieza y separación antes del entrenamiento, y el texto objetivo debe ajustarse al conjunto de caracteres disponible. El repositorio mantiene estas herramientas junto al flujo de formato para repetir el proceso en documentos posteriores."], ["Dar formato imprimible a las líneas generadas", "La síntesis genera la escritura, pero todavía no una hoja lista para imprimir. La fase de formato coloca las líneas en una página, aplica espaciado y resuelve algunos caracteres acentuados mediante una capa de compatibilidad ASCII limitada."], ["Extender el flujo alrededor del modelo original", "El modelo y la síntesis principal siguen perteneciendo al proyecto original. Este repositorio añade preparación de datos, compatibilidad de texto, formato repetible, salida imprimible y notas de entorno para el antiguo conjunto de herramientas Python 2."]]},
    "portfolio-analytics-tool": { facts: [["Entrada", "Posiciones y datos históricos de mercado"], ["Medidas", "Sharpe, Sortino y drawdown"], ["Salida", "Comparaciones de frontera eficiente"]], sections: [["Calcular rendimiento ajustado al riesgo", "Una lista de posiciones no explica cómo se comportan juntas. La herramienta descarga precios, reconstruye la cartera ponderada y compara rendimiento con volatilidad, riesgo a la baja y drawdown máximo."], ["Comparar asignaciones en la frontera eficiente", "En vez de presentar una única respuesta optimizada, la vista de frontera representa miles de asignaciones candidatas. El color expresa el ratio de Sharpe y marca como referencia las carteras de máximo Sharpe y mínima volatilidad."], ["Mantener la optimización en contexto de investigación", "La optimización depende de la ventana histórica, los supuestos y las restricciones. Las carteras generadas sirven para comparar e investigar; no son instrucciones automáticas de inversión."]]},
    habitro: { facts: [["Materias", "Idiomas y matemáticas"], ["Historial", "Seguimiento por ejercicio en SQLite"], ["Interfaz principal", "Aplicación web con React y Vite"]], sections: [["Usar el historial de SQLite para orientar la práctica", "Una ficha estática indica si la respuesta de hoy es correcta, pero no muestra los errores recurrentes. Habitro guarda resultados e intentos anteriores por tipo de ejercicio para que las sesiones posteriores tengan memoria útil."], ["Mantener la práctica de derivadas en una sola vista", "El módulo crea pequeños lotes, puede mezclar preguntas pendientes y muestra la solución solo cuando se solicita. El tamaño, el orden, el ejercicio actual y el historial se mantienen juntos para favorecer el ciclo de intentar, comprobar y revisar."], ["Pasar de Streamlit a React", "La aplicación actual utiliza React y Vite. La versión anterior en Streamlit sigue disponible para experimentación local y comparte la misma idea de práctica diaria estructurada con progreso guardado."]]},
  },
  fr: {
    "ti-nspire-cxii-custom-keyboard-remap": { facts: [["Appareil", "TI-Nspire CX II CAS"], ["Cible", "OS 6.2.0.333 avec Ndless"], ["Portée", "Événements de touches alphabétiques uniquement"]], sections: [["Remapper la saisie alphabétique en QWERTY", "La disposition alphabétique d'origine est lente pour les personnes qui tapent par mémoire musculaire en QWERTY. Le remappage conserve le matériel et ne change que la lettre envoyée au champ de saisie, sans modifier le reste du clavier."], ["Réécrire seulement les lettres dans la file d'événements", "L'application installe un hook résident dans la file d'événements du système. Elle examine les événements A-Z et a-z, remplace l'octet ASCII grâce à une petite table, puis laisse intacts les modificateurs et les touches non alphabétiques."], ["Limiter l'installation à OS 6.2.0.333", "Il ne s'agit pas d'un correctif universel : cette version est conçue et testée pour la CX II CAS sous OS 6.2.0.333. Un mode de vérification affiche le mappage avant l'installation du hook."]]},
    "macro-recorder-plus": { facts: [["Plateforme", "Bureau Windows"], ["Flux", "Enregistrer, modifier, rejouer, exporter"], ["Exports", "Script Python ou EXE facultatif"]], sections: [["Transformer les enregistrements en actions modifiables", "Les événements bruts de souris et de clavier constituent rarement une automatisation terminée. Macro Recorder Plus les transforme en tableau d'actions activables, étiquetables, réordonnables et modifiables, avec des étapes manuelles possibles."], ["Exporter des flux en scripts Python ou exécutables", "Un flux exporté comprend ses dépendances, ressources, lanceur et notes d'exécution. Le même flux peut aussi produire un exécutable Windows avec PyInstaller lorsqu'un fichier unique est plus pratique à transmettre."], ["Ne pas enregistrer les identifiants dans les macros", "Les actions secrètes stockent le nom d'une variable d'environnement, jamais le mot de passe. Les macros partagées ou archivées ne divulguent donc pas d'identifiants."]]},
    calendar: { facts: [["Interface", "Application React monopage"], ["Tâche", "Planification scolaire récurrente"], ["Intégration", "Événements Google Calendar"]], sections: [["Organiser une semaine scolaire récurrente", "Les emplois du temps se répètent alors que contrôles et devoirs changent sans cesse. Homework Calendar rassemble cours, évaluations et tâches dans un flux court afin d'éviter de reconstruire chaque semaine la planification."], ["Transformer les cours et devoirs en événements", "L'interface permet de choisir le type d'événement, la matière et la date avant l'envoi vers Google Calendar. Les cours récurrents restent distincts des rappels ponctuels pour préserver une agenda lisible."], ["Concevoir pour l'usage quotidien", "L'application privilégie des étapes directes et des informations visibles plutôt que des réglages dispersés. La connexion Google est configurée une fois et les préférences peuvent être conservées pour les sessions suivantes."]]},
    "handwriting-pipeline": { facts: [["Amont", "My Text in Your Handwriting"], ["Type", "Extension de flux et outils de bureau"], ["Usage", "Personnel, éducatif et de recherche"]], sections: [["Préparer les échantillons et le texte", "Les échantillons manuscrits numérisés doivent être nettoyés et séparés avant l'entraînement, et le texte cible doit respecter le jeu de caractères disponible. Le dépôt conserve ces outils avec le flux de formatage afin de répéter les mêmes étapes."], ["Mettre les lignes générées en page", "La synthèse produit l'écriture mais pas encore une feuille imprimable. L'étape de formatage place les lignes sur la page, applique les espacements et gère quelques caractères accentués avec une couche de compatibilité ASCII limitée."], ["Étendre le flux autour du modèle amont", "Le modèle et la synthèse principale restent ceux du projet amont. Ce dépôt ajoute la préparation des données, la compatibilité du texte, le formatage reproductible, la sortie imprimable et les notes d'environnement pour les anciens outils Python 2."]]},
    "portfolio-analytics-tool": { facts: [["Entrée", "Positions et historique de marché"], ["Mesures", "Sharpe, Sortino et drawdown"], ["Sortie", "Comparaisons de frontière efficiente"]], sections: [["Calculer une performance ajustée du risque", "Une liste de positions ne dit pas comment elles se comportent ensemble. L'outil récupère les prix, reconstitue le portefeuille pondéré et rapproche rendement, volatilité, risque baissier et drawdown maximal."], ["Comparer les allocations sur la frontière efficiente", "Au lieu de présenter une réponse optimisée isolée, la vue représente des milliers d'allocations candidates. La couleur encode le ratio de Sharpe et les portefeuilles de Sharpe maximal et de volatilité minimale servent de repères."], ["Garder l'optimisation dans un cadre de recherche", "L'optimisation dépend de la période historique, des hypothèses et des contraintes. Les portefeuilles générés sont des cas de comparaison et de recherche, pas des consignes automatiques d'investissement."]]},
    habitro: { facts: [["Matières", "Langues et mathématiques"], ["Historique", "Suivi SQLite par exercice"], ["Interface principale", "Application web React et Vite"]], sections: [["Utiliser l'historique SQLite pour guider la pratique", "Une fiche statique indique si une réponse est juste aujourd'hui, mais pas les erreurs qui reviennent. Habitro enregistre les résultats et tentatives précédentes par type d'exercice afin que les séances suivantes disposent d'une mémoire utile."], ["Garder la pratique des dérivées dans une vue", "Le module crée de petits lots, peut mélanger les questions en attente et ne révèle la solution que sur demande. Taille du lot, ordre, exercice courant et historique restent ensemble pour favoriser le cycle essayer, vérifier et revoir."], ["Passer de Streamlit à React", "L'application actuelle repose sur React et Vite. L'ancienne version Streamlit reste disponible pour l'expérimentation locale et partage l'idée d'une pratique quotidienne structurée avec progression enregistrée."]]},
  },
  de: {
    "ti-nspire-cxii-custom-keyboard-remap": { facts: [["Gerät", "TI-Nspire CX II CAS"], ["Ziel", "OS 6.2.0.333 mit Ndless"], ["Umfang", "Nur alphabetische Tastaturereignisse"]], sections: [["Alphabetische Eingabe auf QWERTY umlegen", "Die alphabetische Standardanordnung ist für Menschen mit QWERTY-Muskelgedächtnis langsam. Das Remapping lässt die Hardware unverändert und ändert nur den Buchstaben im Eingabefeld; der übrige Rechner bleibt gleich bedienbar."], ["Nur Buchstabenereignisse in der OS-Warteschlange ändern", "Die App installiert einen residenten Hook in der Betriebssystem-Ereigniswarteschlange. Sie prüft A-Z- und a-z-Ereignisse, tauscht das ASCII-Byte über eine kleine Tabelle aus und lässt Modifikatoren sowie Nicht-Buchstaben unverändert."], ["Installation auf OS 6.2.0.333 begrenzen", "Dies ist bewusst kein universeller Patch. Der aktuelle Build wurde für die CX II CAS mit OS 6.2.0.333 erstellt und getestet; ein Prüfmodus zeigt das Mapping vor der Installation."]]},
    "macro-recorder-plus": { facts: [["Plattform", "Windows-Desktop"], ["Ablauf", "Aufzeichnen, bearbeiten, abspielen, exportieren"], ["Exporte", "Python-Skript oder optionales EXE"]], sections: [["Aufzeichnungen in bearbeitbare Aktionen verwandeln", "Rohe Maus- und Tastaturereignisse sind selten schon eine fertige Automatisierung. Macro Recorder Plus überführt sie in eine Tabelle aus aktivierbaren, beschriftbaren, umsortierbaren und editierbaren Aktionen; manuelle Schritte können ergänzt werden."], ["Abläufe als Python-Skripte oder EXEs exportieren", "Ein exportierter Ablauf enthält Abhängigkeiten, Dateien, Starter und Ausführungshinweise. Derselbe Ablauf kann mit PyInstaller auch eine Windows-EXE erzeugen, wenn eine einzelne Übergabedatei praktischer ist."], ["Zugangsdaten aus Makrodateien heraushalten", "Geheime Aktionen speichern den Namen einer Umgebungsvariable statt eines Passworts. So legen geteilte oder archivierte Makros keine Zugangsdaten offen."]]},
    calendar: { facts: [["Oberfläche", "React-Single-Page-App"], ["Aufgabe", "Wiederkehrende Schulplanung"], ["Integration", "Google-Calendar-Ereignisse"]], sections: [["Eine wiederkehrende Schulwoche organisieren", "Stundenpläne wiederholen sich, Klassenarbeiten und Hausaufgaben ändern sich aber laufend. Homework Calendar bündelt Unterricht, Prüfungen und Aufgaben in einem kurzen Ablauf, damit die Wochenplanung nicht jedes Mal neu entsteht."], ["Unterricht und Aufgaben in Kalenderereignisse verwandeln", "Vor dem Senden an Google Calendar werden Ereignisart, Fach und Datum gewählt. Wiederkehrende Stunden bleiben von einzelnen Erinnerungen getrennt, sodass der Kalender übersichtlich bleibt."], ["Für die tägliche Nutzung gestalten", "Die Anwendung bevorzugt direkte Schritte und sichtbare Informationen gegenüber verstreuten Einstellungsseiten. Die Google-Verbindung wird einmal eingerichtet und Präferenzen können für spätere Sitzungen gespeichert werden."]]},
    "handwriting-pipeline": { facts: [["Upstream", "My Text in Your Handwriting"], ["Projekttyp", "Workflow-Erweiterung und Desktop-Werkzeuge"], ["Einsatz", "Persönlich, Bildung und Forschung"]], sections: [["Proben und Text für die Synthese vorbereiten", "Gescanntes Handschriftmaterial muss vor dem Training bereinigt und aufgeteilt werden; der Zieltext muss zum verfügbaren Zeichensatz passen. Das Repository hält diese Werkzeuge neben der Formatierung bereit, damit die Schritte wiederholbar bleiben."], ["Generierte Zeilen druckfertig formatieren", "Die Synthese erzeugt Schrift, aber noch kein druckbares Blatt. Die Formatierungsphase platziert die Zeilen auf einer Seite, wendet Abstände an und behandelt einige Akzentzeichen über eine begrenzte ASCII-Kompatibilitätsschicht."], ["Den Workflow um das Upstream-Modell erweitern", "Modell und Kern-Synthese bleiben im Upstream-Projekt. Dieses Repository ergänzt Datenvorbereitung, Textkompatibilität, wiederholbare Formatierung, Druckausgabe und Umgebungsnotizen für die älteren Python-2-Werkzeuge."]]},
    "portfolio-analytics-tool": { facts: [["Eingabe", "Bestände und historische Marktdaten"], ["Kennzahlen", "Sharpe, Sortino und Drawdown"], ["Ausgabe", "Efficient-Frontier-Vergleiche"]], sections: [["Risikobereinigte Leistung berechnen", "Eine Bestandsliste erklärt nicht, wie Positionen zusammen wirken. Das Tool lädt Kurse, rekonstruiert das gewichtete Portfolio und stellt Rendite neben Volatilität, Abwärtsrisiko und maximalen Drawdown."], ["Allokationen auf der Efficient Frontier vergleichen", "Statt eine einzelne optimierte Antwort ohne Kontext zu zeigen, zeichnet die Ansicht Tausende Kandidaten ein. Farben kodieren die Sharpe Ratio; Maximum-Sharpe- und Minimum-Volatilitätsportfolios dienen als Referenz."], ["Optimierung im Forschungskontext halten", "Optimierung hängt vom historischen Zeitraum, Annahmen und Beschränkungen ab. Die erzeugten Portfolios sind Vergleichs- und Forschungsfälle, keine automatischen Anlageanweisungen."]]},
    habitro: { facts: [["Fächer", "Sprachen und Mathematik"], ["Verlauf", "SQLite-Tracking pro Übung"], ["Primäre Oberfläche", "React- und Vite-Web-App"]], sections: [["SQLite-Verlauf für spätere Übung nutzen", "Ein statisches Arbeitsblatt zeigt, ob die heutige Antwort stimmt, nicht aber wiederkehrende Fehler. Habitro speichert Ergebnisse und frühere Versuche je Übungstyp, damit spätere Sitzungen ein nützliches Gedächtnis haben."], ["Ableitungsübungen in einer Ansicht halten", "Das Modul erstellt kleine Stapel, kann offene Fragen mischen und zeigt die Lösung nur auf Anfrage. Stapelgröße, Reihenfolge, aktuelle Aufgabe und Verlauf bleiben zusammen und unterstützen den Ablauf Versuch, Kontrolle, Speicherung und Wiederholung."], ["Von Streamlit zu React wechseln", "Die aktuelle Anwendung verwendet React und Vite. Die frühere Streamlit-Version bleibt für lokale Experimente verfügbar und teilt die Idee strukturierter täglicher Übung mit gespeichertem Fortschritt."]]},
  },
  hu: {
    "ti-nspire-cxii-custom-keyboard-remap": { facts: [["Eszköz", "TI-Nspire CX II CAS"], ["Cél", "OS 6.2.0.333 Ndless-szel"], ["Hatókör", "Csak betűs billentyűesemények"]], sections: [["Betűbevitel QWERTY-kiosztásra alakítása", "A számológép eredeti betűrendes kiosztása lassú annak, aki QWERTY izommemóriával gépel. Az átkiosztás változatlanul hagyja a hardvert, és csak a beviteli mezőbe kerülő betűt módosítja."], ["Csak a betűesemények átírása az OS sorában", "Az alkalmazás rezidens hookot telepít az operációs rendszer eseménysorába. Az A-Z és a-z eseményeket vizsgálja, egy kis táblázattal cseréli az ASCII bájtot, a módosítókat és nem betűs billentyűket pedig érintetlenül hagyja."], ["Telepítés korlátozása OS 6.2.0.333-ra", "Ez szándékosan nem univerzális javítás. A jelenlegi build a CX II CAS OS 6.2.0.333 változatához készült és azon lett tesztelve; ellenőrző mód mutatja a kiosztást telepítés előtt."]]},
    "macro-recorder-plus": { facts: [["Platform", "Windows asztali alkalmazás"], ["Munkafolyamat", "Rögzítés, szerkesztés, lejátszás, export"], ["Export", "Python-szkript vagy opcionális EXE"]], sections: [["A rögzítések szerkeszthető műveletekké alakítása", "A nyers egér- és billentyűzetesemények ritkán jelentenek kész automatizálást. A Macro Recorder Plus szerkeszthető, felcímkézhető és átrendezhető műveletek táblájává alakítja őket, kézzel hozzáadható lépésekkel."], ["Munkafolyamatok exportálása Python-szkriptként vagy EXE-ként", "Az exportált munkafolyamat függőségeket, erőforrásokat, indítót és futtatási megjegyzéseket tartalmaz. Ugyanez a munkafolyamat PyInstallerrel Windows EXE-t is létrehozhat, ha egyetlen átadható fájl praktikusabb."], ["Hitelesítő adatok távol tartása a makróktól", "A titkos műveletek jelszó helyett környezeti változó nevét tárolják. Így a megosztott vagy archivált makrók nem fednek fel belépési adatokat."]]},
    calendar: { facts: [["Felület", "React egyoldalas alkalmazás"], ["Feladat", "Ismétlődő iskolai tervezés"], ["Integráció", "Google Calendar események"]], sections: [["Ismétlődő iskolai hét szervezése", "Az órarendek ismétlődnek, a dolgozatok és házi feladatok viszont folyton változnak. A Homework Calendar rövid munkafolyamatba rendezi az órákat, értékeléseket és teendőket, így nem kell a heti tervet mindig újra felépíteni."], ["Órák és feladatok naptáreseménnyé alakítása", "A felhasználó kiválasztja az esemény típusát, a tantárgyat és a dátumot, mielőtt elküldi azt a Google Calendarba. Az ismétlődő órák külön maradnak az egyszeri emlékeztetőktől, ezért a naptár áttekinthető."], ["Mindennapi használatra tervezve", "Az alkalmazás a közvetlen lépéseket és a látható információkat részesíti előnyben a szétszórt beállítási képernyőkkel szemben. A Google-kapcsolatot egyszer kell beállítani, a beállítások pedig megőrizhetők."]]},
    "handwriting-pipeline": { facts: [["Alapprojekt", "My Text in Your Handwriting"], ["Projekt típusa", "Munkafolyamat-bővítés és asztali eszközök"], ["Használat", "Személyes, oktatási és kutatási"]], sections: [["Minták és szöveg előkészítése szintézishez", "A beszkennelt kézírásmintákat tanítás előtt tisztítani és szétválasztani kell, a célszövegnek pedig illeszkednie kell az elérhető karakterkészlethez. A tároló ezeket az eszközöket a formázási folyamattal együtt őrzi meg."], ["A generált sorok nyomtatható formázása", "A szintézis kézírást készít, de még nem nyomtatható lapot. A formázási szakasz oldalra helyezi a sorokat, beállítja a térközöket, és néhány ékezetes karaktert korlátozott ASCII-kompatibilitással kezel."], ["Az upstream modell körüli folyamat bővítése", "A modell és az alapvető szintézis az upstream projektben marad. Ez a tároló adat-előkészítést, szövegkompatibilitást, megismételhető formázást, nyomtatási kimenetet és régebbi Python 2-es eszközökhöz környezeti jegyzeteket ad hozzá."]]},
    "portfolio-analytics-tool": { facts: [["Bemenet", "Részvényállományok és piaci előzmények"], ["Mutatók", "Sharpe, Sortino és drawdown"], ["Kimenet", "Hatékony határ összehasonlítások"]], sections: [["Kockázattal korrigált teljesítmény számítása", "Egy állománylista nem mondja el, hogyan viselkednek együtt a pozíciók. Az eszköz árfolyam-előzményeket tölt le, újraépíti a súlyozott portfóliót, és a hozamot volatilitással, lefelé mutató kockázattal és maximális visszaeséssel veti össze."], ["Allokációk összehasonlítása a hatékony határon", "Egyetlen optimalizált válasz helyett a nézet jelölt allokációk ezreit ábrázolja. A szín a Sharpe rátát jelöli, a maximális Sharpe- és minimális volatilitású portfóliók pedig referenciapontok."], ["Az optimalizálás kutatási kontextusban tartása", "Az optimalizálás a történelmi időablaktól, feltételezésektől és korlátozásoktól függ. A létrehozott portfóliók összehasonlításra és kutatásra szolgálnak, nem automatikus befektetési utasítások."]]},
    habitro: { facts: [["Tantárgyak", "Nyelvek és matematika"], ["Előzmények", "SQLite gyakorlatonkénti követés"], ["Elsődleges felület", "React és Vite webalkalmazás"]], sections: [["SQLite-előzmények használata a gyakorlás alakítására", "Egy statikus feladatlap megmutatja, hogy a mai válasz helyes-e, de nem jelzi a visszatérő hibákat. A Habitro gyakorlatonként tárolja az eredményeket és korábbi próbálkozásokat, ezért a későbbi alkalmak hasznos emlékezettel indulnak."], ["Deriválásgyakorlás egy nézetben", "A modul kis feladatsorokat készít, keverheti a függőben lévő kérdéseket, és csak kérésre fedi fel a megoldást. A méret, sorrend, aktuális feladat és előzmények együtt maradnak, támogatva a próbálkozás, ellenőrzés és ismétlés körét."], ["Átállás Streamlitről Reactre", "A jelenlegi alkalmazás Reactet és Vite-ot használ. A korábbi Streamlit-változat helyi kísérletezéshez továbbra is elérhető, és ugyanazt a strukturált napi gyakorlást, mentett fejlődést képviseli."]]},
  },
};

export function getLocalizedCaseStudy(route, language) {
  const translation = CASE_STUDY_TRANSLATIONS[language]?.[route.id];
  if (!translation) return route.caseStudy;

  return {
    ...route.caseStudy,
    facts: translation.facts.map(([label, value]) => ({ label, value })),
    sections: translation.sections.map(([title, paragraph]) => ({ title, paragraphs: [paragraph] })),
  };
}

const PROJECT_ID_BY_CASE_STUDY = {
  "case-study-keyboard-remap": "ti-nspire-cxii-custom-keyboard-remap",
  "case-study-macro-recorder": "macro-recorder-plus",
  "case-study-homework-calendar": "calendar",
  "case-study-handwriting": "handwriting-pipeline",
  "case-study-portfolio-analytics": "portfolio-analytics-tool",
  "case-study-habitro": "habitro",
};

export function getLocalizedCaseStudyIntro(route, language, content) {
  const projectId = PROJECT_ID_BY_CASE_STUDY[route.id];
  const project = PROJECTS_CONTENT.find((item) => item.id === projectId);
  const translation = project?.translations?.[language];
  if (!translation) return content;

  return {
    ...content,
    heading: translation.title,
    description: translation.summary,
  };
}
