export const LANGUAGE_OPTIONS = [
  { code: "en", label: "EN" },
  { code: "es", label: "ES" },
  { code: "fr", label: "FR" },
  { code: "de", label: "DE" },
  { code: "hu", label: "HU" },
];

export const PAGES = ["home", "projects", "experience", "whoami"];

export const PROFILE = {
  name: "Marton Vegh",
  location: "Mallorca, Spain",
  email: "martonvegh2009@gmail.com",
  githubHandle: "Martonveghcode",
  githubUrl: "https://github.com/Martonveghcode",
  instagramUrl: "https://www.instagram.com/marton.alt",
  profileImage: "/profile/marton-vegh-portrait.jpg",
  sportsImage: "/profile/marton-vegh-canoe-sprint.jpg",
};

export const STACK = {
  core: ["React", "JavaScript", "HTML/CSS"],
  learning: ["Python", "C++"],
};

export const CV_LINKS = {
  en: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  es: "https://docs.google.com/document/d/1CjebLBCKT-dVCapR6NFn3rT9jIjyMSaEpMWFKl__EDo/edit?usp=sharing",
  fr: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  de: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  hu: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
};

export const translations = {
  en: {
    nav: { home: "Home", projects: "Projects", papers: "Papers", experience: "Experience", whoami: "Who Am I" },
    heroTagline: "Penta-lingual aspiring quantitative financial engineer",
    heroSub: "Focused on practical solutions that solve real problems.",
    aboutTitle: "General information",
    aboutBlurb:
      "Student developer studying in spain with a passion for politics, finance and math. Based in mallorca. Some experience in react web design and currently studying a MIT micromasters in finance.",
    languagesTitle: "Languages",
    languagesList: [
      "Hungarian (native)",
      "English (fluent)",
      "Spanish (fluent)",
      "French (fluent)",
      "Catalan (learning)",
    ],
    stackTitle: "What I use",
    stackCoreLabel: "Core",
    stackLearningLabel: "Learning",
    passionsTitle: "Interests",
    passionsList: ["Automation", "Classical art", "Books", "Pure mathematics", "Programming and algorithms", "Sports"],
    githubTitle: "GitHub heatmap",
    projectsTitle: "Projects",
    papersTitle: "Papers",
    experienceTitle: "Experience",
    whoAmITitle: "Who Am I",
    favoriteBooksTitle: "My top 15 favourite books",
    favoritePaintingsTitle: "My top 5 favourite paintings",
    worstBooksTitle: "Top 3 worst books",
    sportsAchievementsTitle: "Canoe sprint achievements",
    links: { live: "Live", github: "GitHub", paper: "View paper" },
  },
  es: {
    nav: { home: "Inicio", projects: "Proyectos", papers: "Papers", experience: "Experiencia", whoami: "Quien soy" },
    heroTagline: "Aspirante a ingeniero financiero cuantitativo que habla 5 idiomas",
    heroSub: "Enfocado en soluciones practicas que resuelven problemas reales.",
    aboutTitle: "Quien soy",
    aboutBlurb:
      "Estudiante desarrollador que estudia en Espana con pasion por la politica, las finanzas y las matematicas. Vive en Mallorca. Tiene algo de experiencia en diseno web con React y actualmente estudia un MicroMasters del MIT en finanzas.",
    languagesTitle: "Idiomas",
    languagesList: ["Hungaro (nativo)", "Ingles (fluido)", "Espanol (fluido)", "Frances (fluido)", "Catalan (aprendiendo)"],
    stackTitle: "Que uso",
    stackCoreLabel: "Nucleo",
    stackLearningLabel: "Aprendiendo",
    passionsTitle: "Intereses",
    passionsList: ["Automatizacion", "Arte clasico", "Libros", "Matematicas puras", "Programacion y algoritmos", "Deporte"],
    githubTitle: "Heatmap de GitHub",
    projectsTitle: "Proyectos",
    papersTitle: "Papers",
    experienceTitle: "Experiencia",
    whoAmITitle: "Quien soy",
    favoriteBooksTitle: "Mis 15 libros favoritos",
    favoritePaintingsTitle: "Mis 5 pinturas favoritas",
    worstBooksTitle: "Top 3 peores libros",
    sportsAchievementsTitle: "Logros en piraguismo de velocidad",
    links: { live: "Live", github: "GitHub", paper: "Ver paper" },
  },
  fr: {
    nav: { home: "Accueil", projects: "Projets", papers: "Papiers", experience: "Experience", whoami: "Qui je suis" },
    heroTagline: "Aspirant ingenieur financier quantitatif parlant 5 langues",
    heroSub: "Centre sur des solutions pratiques qui resolvent de vrais problemes.",
    aboutTitle: "Qui je suis",
    aboutBlurb:
      "Etudiant developpeur en Espagne avec une passion pour la politique, la finance et les mathematiques. Base a Majorque. Il a un peu d'experience en web design avec React et suit actuellement un MicroMasters du MIT en finance.",
    languagesTitle: "Langues",
    languagesList: ["Hongrois (natif)", "Anglais (courant)", "Espagnol (courant)", "Francais (courant)", "Catalan (en apprentissage)"],
    stackTitle: "Ce que j'utilise",
    stackCoreLabel: "Noyau",
    stackLearningLabel: "Apprentissage",
    passionsTitle: "Interets",
    passionsList: ["Automatisation", "Art classique", "Livres", "Mathematiques pures", "Programmation et algorithmes", "Sport"],
    githubTitle: "Heatmap GitHub",
    projectsTitle: "Projets",
    papersTitle: "Papiers",
    experienceTitle: "Experience",
    whoAmITitle: "Qui je suis",
    favoriteBooksTitle: "Mes 15 livres preferes",
    favoritePaintingsTitle: "Mes 5 peintures preferees",
    worstBooksTitle: "Top 3 pires livres",
    sportsAchievementsTitle: "Palmares en canoe sprint",
    links: { live: "Live", github: "GitHub", paper: "Voir le papier" },
  },
  de: {
    nav: { home: "Start", projects: "Projekte", papers: "Papers", experience: "Erfahrung", whoami: "Wer ich bin" },
    heroTagline: "Funfsprachiger angehender quantitativer Finanzingenieur",
    heroSub: "Fokus auf praktische Losungen, die reale Probleme losen.",
    aboutTitle: "Wer ich bin",
    aboutBlurb:
      "Studentischer Entwickler in Spanien mit einer Leidenschaft fur Politik, Finanzen und Mathematik. Lebt auf Mallorca. Hat etwas Erfahrung mit React-Webdesign und studiert derzeit ein MIT MicroMasters in Finance.",
    languagesTitle: "Sprachen",
    languagesList: ["Ungarisch (Muttersprache)", "Englisch (fliessend)", "Spanisch (fliessend)", "Franzosisch (fliessend)", "Katalanisch (lernend)"],
    stackTitle: "Was ich nutze",
    stackCoreLabel: "Kern",
    stackLearningLabel: "Lernen",
    passionsTitle: "Interessen",
    passionsList: ["Automatisierung", "Klassische Kunst", "Bucher", "Reine Mathematik", "Programmierung und Algorithmen", "Sport"],
    githubTitle: "GitHub-Heatmap",
    projectsTitle: "Projekte",
    papersTitle: "Papers",
    experienceTitle: "Erfahrung",
    whoAmITitle: "Wer ich bin",
    favoriteBooksTitle: "Meine Top 15 Lieblingsbucher",
    favoritePaintingsTitle: "Meine 5 Lieblingsgemalde",
    worstBooksTitle: "Top 3 schlechteste Bucher",
    sportsAchievementsTitle: "Erfolge im Kanusprint",
    links: { live: "Live", github: "GitHub", paper: "Papier ansehen" },
  },
  hu: {
    nav: { home: "Kezdolap", projects: "Projektek", papers: "Tanulmanyok", experience: "Tapasztalat", whoami: "Ki vagyok" },
    heroTagline: "Ot nyelven beszelo leendo kvantitativ penzugyi mernok",
    heroSub: "Gyakorlati, valos problemakat megoldo megoldasokra fokuszalok.",
    aboutTitle: "Ki vagyok",
    aboutBlurb:
      "Spanyolorszagban tanulo diak fejleszto vagyok, akit a politika, a penzugy es a matematika erdekel. Mallorcan elek. Van nemi tapasztalatom React webdizajnban, es jelenleg az MIT penzugyi MicroMasters kepzeset tanulom.",
    languagesTitle: "Nyelvek",
    languagesList: ["Magyar (anyanyelv)", "Angol (folyekony)", "Spanyol (folyekony)", "Francia (folyekony)", "Katalan (tanulas alatt)"],
    stackTitle: "Amit hasznalok",
    stackCoreLabel: "Alap",
    stackLearningLabel: "Tanulom",
    passionsTitle: "Erdeklodes",
    passionsList: ["Automatizalas", "Klasszikus muveszet", "Konyvek", "Tiszta matematika", "Programozas es algoritmusok", "Sport"],
    githubTitle: "GitHub heatmap",
    projectsTitle: "Projektek",
    papersTitle: "Tanulmanyok",
    experienceTitle: "Tapasztalat",
    whoAmITitle: "Ki vagyok",
    favoriteBooksTitle: "A top 15 kedvenc konyvem",
    favoritePaintingsTitle: "Az 5 kedvenc festmenyem",
    worstBooksTitle: "Top 3 legrosszabb konyv",
    sportsAchievementsTitle: "Kajak sprint eredmenyek",
    links: { live: "Elo", github: "GitHub", paper: "Tanulmany megnyitasa" },
  },
};
