export const LANGUAGE_OPTIONS = [
  { code: "en", label: "EN" },
  { code: "es", label: "ES" },
  { code: "fr", label: "FR" },
  { code: "de", label: "DE" },
  { code: "hu", label: "HU" },
];

export const PAGES = ["home", "projects", "experience", "whoami"];

export const PROFILE = {
  name: "Marton Vegh",
  location: "Mallorca, Spain",
  email: "martonvegh2009@gmail.com",
  githubHandle: "Martonveghcode",
  githubUrl: "https://github.com/Martonveghcode",
  instagramUrl: "https://www.instagram.com/marton.alt",
  profileImage: "/profile/marton-vegh-portrait.jpg",
  sportsImage: "/profile/marton-vegh-canoe-sprint.jpg",
};

export const STACK = {
  core: ["React", "JavaScript", "HTML/CSS"],
  learning: ["Python", "C++"],
};

export const CV_LINKS = {
  en: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  es: "https://docs.google.com/document/d/1CjebLBCKT-dVCapR6NFn3rT9jIjyMSaEpMWFKl__EDo/edit?usp=sharing",
  fr: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  de: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  hu: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
};

export const translations = {
  en: {
    nav: { home: "Home", projects: "Projects", experience: "Experience", whoami: "Who Am I" },
    heroTagline: "Aspiring quantitative financial engineer",
    getInTouch: "Get in touch",
    ui: {
      menu: "Menu",
      close: "Close",
      primaryNavLabel: "Primary",
      languageLabel: "Language",
      themeToggleLabel: "Toggle theme",
      themeDark: "Dark",
      themeLight: "Light",
    },
    contactForm: {
      shellLabel: "Get in touch",
      dragLabel: "Drag contact form",
      title: "Send a message",
      name: "Name",
      email: "Email",
      message: "Message",
      messagePlaceholder: "Write a short message",
      close: "Close",
      send: "Send",
      sending: "Sending...",
      error: "Could not send your message. Check the database rules and try again.",
    },
    aboutTitle: "General information",
    aboutBlurb:
      "Pentalingual student developer based in Mallorca, Spain, focused on geopolitics, finance, and mathematics. I build React interfaces and practical tools in Python, JavaScript, C, and C++, have authored multiple independent papers, study corporate finance and probability, and compete as a national-level athlete.",
    languagesTitle: "Languages",
    languagesList: [
      "Hungarian (native)",
      "English (fluent)",
      "Spanish (fluent)",
      "French (fluent)",
      "Catalan (learning)",
    ],
    stackTitle: "What I use",
    stackCoreLabel: "Core",
    stackLearningLabel: "Learning",
    passionsTitle: "Interests",
    passionsList: ["Automation", "Classical art", "Books", "Pure mathematics", "Programming and algorithms", "Sports"],
    githubTitle: "GitHub heatmap",
    projectsTitle: "Personal projects",
    experienceTitle: "Experience",
    whoAmITitle: "Who Am I",
    favoriteBooksTitle: "My top 15 favourite books",
    favoritePaintingsTitle: "My top 5 favourite paintings",
    worstBooksTitle: "Top 3 worst books",
    sportsAchievementsTitle: "Canoe sprint achievements",
    links: { live: "Live", github: "GitHub" },
  },
  es: {
    nav: { home: "Inicio", projects: "Proyectos", experience: "Experiencia", whoami: "Quien soy" },
    heroTagline: "Aspirante a ingeniero financiero cuantitativo",
    getInTouch: "Ponte en contacto",
    ui: {
      menu: "Menu",
      close: "Cerrar",
      primaryNavLabel: "Principal",
      languageLabel: "Idioma",
      themeToggleLabel: "Cambiar tema",
      themeDark: "Oscuro",
      themeLight: "Claro",
    },
    contactForm: {
      shellLabel: "Ponte en contacto",
      dragLabel: "Mover formulario de contacto",
      title: "Enviar un mensaje",
      name: "Nombre",
      email: "Correo",
      message: "Mensaje",
      messagePlaceholder: "Escribe un mensaje corto",
      close: "Cerrar",
      send: "Enviar",
      sending: "Enviando...",
      error: "No se pudo enviar tu mensaje. Revisa las reglas de la base de datos e intentalo de nuevo.",
    },
    aboutTitle: "Quien soy",
    aboutBlurb:
      "Estudiante desarrollador pentalingue basado en Mallorca, Espana, centrado en geopolitica, finanzas y matematicas. Construyo interfaces en React y herramientas practicas en Python, JavaScript, C y C++, he escrito varios papers independientes, estudio finanzas corporativas y probabilidad, y compito como atleta de nivel nacional.",
    languagesTitle: "Idiomas",
    languagesList: ["Hungaro (nativo)", "Ingles (fluido)", "Espanol (fluido)", "Frances (fluido)", "Catalan (aprendiendo)"],
    stackTitle: "Que uso",
    stackCoreLabel: "Nucleo",
    stackLearningLabel: "Aprendiendo",
    passionsTitle: "Intereses",
    passionsList: ["Automatizacion", "Arte clasico", "Libros", "Matematicas puras", "Programacion y algoritmos", "Deporte"],
    githubTitle: "Heatmap de GitHub",
    projectsTitle: "Proyectos personales",
    experienceTitle: "Experiencia",
    whoAmITitle: "Quien soy",
    favoriteBooksTitle: "Mis 15 libros favoritos",
    favoritePaintingsTitle: "Mis 5 pinturas favoritas",
    worstBooksTitle: "Top 3 peores libros",
    sportsAchievementsTitle: "Logros en piraguismo de velocidad",
    links: { live: "Live", github: "GitHub" },
  },
  fr: {
    nav: { home: "Accueil", projects: "Projets", experience: "Experience", whoami: "Qui je suis" },
    heroTagline: "Aspirant ingenieur financier quantitatif",
    getInTouch: "Me contacter",
    ui: {
      menu: "Menu",
      close: "Fermer",
      primaryNavLabel: "Navigation principale",
      languageLabel: "Langue",
      themeToggleLabel: "Changer le theme",
      themeDark: "Sombre",
      themeLight: "Clair",
    },
    contactForm: {
      shellLabel: "Me contacter",
      dragLabel: "Deplacer le formulaire de contact",
      title: "Envoyer un message",
      name: "Nom",
      email: "E-mail",
      message: "Message",
      messagePlaceholder: "Ecrivez un court message",
      close: "Fermer",
      send: "Envoyer",
      sending: "Envoi...",
      error: "Impossible d'envoyer votre message. Verifiez les regles de la base de donnees et reessayez.",
    },
    aboutTitle: "Qui je suis",
    aboutBlurb:
      "Etudiant developpeur pentalingue base a Majorque, en Espagne, centre sur la geopolitique, la finance et les mathematiques. Je construis des interfaces React et des outils pratiques en Python, JavaScript, C et C++, j'ai redige plusieurs articles independants, j'etudie la finance d'entreprise et les probabilites, et je compete comme athlete de niveau national.",
    languagesTitle: "Langues",
    languagesList: ["Hongrois (natif)", "Anglais (courant)", "Espagnol (courant)", "Francais (courant)", "Catalan (en apprentissage)"],
    stackTitle: "Ce que j'utilise",
    stackCoreLabel: "Noyau",
    stackLearningLabel: "Apprentissage",
    passionsTitle: "Interets",
    passionsList: ["Automatisation", "Art classique", "Livres", "Mathematiques pures", "Programmation et algorithmes", "Sport"],
    githubTitle: "Heatmap GitHub",
    projectsTitle: "Projets personels",
    experienceTitle: "Experience",
    whoAmITitle: "Qui je suis",
    favoriteBooksTitle: "Mes 15 livres preferes",
    favoritePaintingsTitle: "Mes 5 peintures preferees",
    worstBooksTitle: "Top 3 pires livres",
    sportsAchievementsTitle: "Palmares en canoe sprint",
    links: { live: "Live", github: "GitHub" },
  },
  de: {
    nav: { home: "Start", projects: "Projekte", experience: "Erfahrung", whoami: "Wer ich bin" },
    heroTagline: "Angehender quantitativer Finanzingenieur",
    getInTouch: "Kontakt",
    ui: {
      menu: "Menu",
      close: "Schliessen",
      primaryNavLabel: "Hauptnavigation",
      languageLabel: "Sprache",
      themeToggleLabel: "Thema wechseln",
      themeDark: "Dunkel",
      themeLight: "Hell",
    },
    contactForm: {
      shellLabel: "Kontakt",
      dragLabel: "Kontaktformular verschieben",
      title: "Nachricht senden",
      name: "Name",
      email: "E-Mail",
      message: "Nachricht",
      messagePlaceholder: "Schreibe eine kurze Nachricht",
      close: "Schliessen",
      send: "Senden",
      sending: "Wird gesendet...",
      error: "Deine Nachricht konnte nicht gesendet werden. Pruefe die Datenbankregeln und versuche es erneut.",
    },
    aboutTitle: "Wer ich bin",
    aboutBlurb:
      "Funfsprachiger studentischer Entwickler auf Mallorca, Spanien, mit Fokus auf Geopolitik, Finanzen und Mathematik. Ich baue React-Oberflachen und praktische Tools in Python, JavaScript, C und C++, habe mehrere unabhangige Papers verfasst, studiere Corporate Finance und Wahrscheinlichkeit, und trete als Athlet auf nationalem Niveau an.",
    languagesTitle: "Sprachen",
    languagesList: ["Ungarisch (Muttersprache)", "Englisch (fliessend)", "Spanisch (fliessend)", "Franzosisch (fliessend)", "Katalanisch (lernend)"],
    stackTitle: "Was ich nutze",
    stackCoreLabel: "Kern",
    stackLearningLabel: "Lernen",
    passionsTitle: "Interessen",
    passionsList: ["Automatisierung", "Klassische Kunst", "Bucher", "Reine Mathematik", "Programmierung und Algorithmen", "Sport"],
    githubTitle: "GitHub-Heatmap",
    projectsTitle: "Persönliche projekte",
    experienceTitle: "Erfahrung",
    whoAmITitle: "Wer ich bin",
    favoriteBooksTitle: "Meine Top 15 Lieblingsbucher",
    favoritePaintingsTitle: "Meine 5 Lieblingsgemalde",
    worstBooksTitle: "Top 3 schlechteste Bucher",
    sportsAchievementsTitle: "Erfolge im Kanusprint",
    links: { live: "Live", github: "GitHub" },
  },
  hu: {
    nav: { home: "Kezdolap", projects: "Projektek", experience: "Tapasztalat", whoami: "Ki vagyok" },
    heroTagline: "Leendo kvantitativ penzugyi mernok",
    getInTouch: "Lepj kapcsolatba",
    ui: {
      menu: "Menu",
      close: "Bezar",
      primaryNavLabel: "Fo navigacio",
      languageLabel: "Nyelv",
      themeToggleLabel: "Tema valtasa",
      themeDark: "Sotet",
      themeLight: "Vilagos",
    },
    contactForm: {
      shellLabel: "Lepj kapcsolatba",
      dragLabel: "Kapcsolati urlap mozgatasa",
      title: "Uzenet kuldese",
      name: "Nev",
      email: "Email",
      message: "Uzenet",
      messagePlaceholder: "Irj egy rovid uzenetet",
      close: "Bezar",
      send: "Kuldes",
      sending: "Kuldes...",
      error: "Nem sikerult elkuldeni az uzenetet. Ellenorizd az adatbazis szabalyait, majd probald ujra.",
    },
    aboutTitle: "Ki vagyok",
    aboutBlurb:
      "Ot nyelven beszelo diak fejleszto vagyok Mallorcan, Spanyolorszagban, geopolitikai, penzugyi es matematikai fokusszal. React feluleteket es gyakorlati eszkozoket epitek Pythonban, JavaScriptben, C-ben es C++-ban, tobb fuggetlen tanulmanyt irtam, vallalati penzugyet es valoszinusegszamitast tanulok, es orszagos szintu sportolokent versenyzek.",
    languagesTitle: "Nyelvek",
    languagesList: ["Magyar (anyanyelv)", "Angol (folyekony)", "Spanyol (folyekony)", "Francia (folyekony)", "Katalan (tanulas alatt)"],
    stackTitle: "Amit hasznalok",
    stackCoreLabel: "Alap",
    stackLearningLabel: "Tanulom",
    passionsTitle: "Erdeklodes",
    passionsList: ["Automatizalas", "Klasszikus muveszet", "Konyvek", "Tiszta matematika", "Programozas es algoritmusok", "Sport"],
    githubTitle: "GitHub heatmap",
    projectsTitle: "személyes projektek",
    experienceTitle: "Tapasztalat",
    whoAmITitle: "Ki vagyok",
    favoriteBooksTitle: "A top 15 kedvenc konyvem",
    favoritePaintingsTitle: "Az 5 kedvenc festmenyem",
    worstBooksTitle: "Top 3 legrosszabb konyv",
    sportsAchievementsTitle: "Kajak sprint eredmenyek",
    links: { live: "Elo", github: "GitHub" },
  },
};
