export const LANGUAGE_OPTIONS = [
  { code: "en", label: "EN" },
  { code: "es", label: "ES" },
  { code: "fr", label: "FR" },
  { code: "de", label: "DE" },
  { code: "hu", label: "HU" },
];

export const PAGES = ["home", "projects", "experience", "whoami"];

export const PROFILE = {
  name: "Marton Vegh",
  location: "Mallorca, Spain",
  email: "martonvegh2009@gmail.com",
  githubHandle: "Martonveghcode",
  githubUrl: "https://github.com/Martonveghcode",
  instagramUrl: "https://www.instagram.com/marton.alt",
  sportsImage: "https://i.ibb.co/PZmb2gTS/Whats-App-Image-2025-12-19-at-10-48-27.jpg",
};

export const STACK = {
  core: ["React", "JavaScript", "HTML/CSS"],
  learning: ["Python", "C++"],
};

export const CV_LINKS = {
  en: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  es: "https://docs.google.com/document/d/1CjebLBCKT-dVCapR6NFn3rT9jIjyMSaEpMWFKl__EDo/edit?usp=sharing",
  fr: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  de: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
  hu: "https://docs.google.com/document/d/1ySTOOs4WWW-R1iwxHmrNS7cDCPykq0WpGquFvU6jHkg/edit?usp=sharing",
};

export const translations = {
  en: {
    nav: { home: "Home", projects: "Projects", papers: "Papers", experience: "Experience", whoami: "Who Am I" },
    heroTagline: "16 year-old developer",
    heroSub: "Focused on practical solutions that solve real problems.",
    aboutTitle: "Who I am",
    aboutBlurb:
      "Student developer studying in Spain with a passion for maths. Based in Mallorca. Started programming recently by learning web design, moving onto more data-science oriented programming.",
    languagesTitle: "Languages",
    languagesList: [
      "Hungarian (native)",
      "English (fluent)",
      "Spanish (fluent)",
      "French (fluent)",
      "Catalan (learning)",
    ],
    stackTitle: "What I use",
    stackCoreLabel: "Core",
    stackLearningLabel: "Learning",
    passionsTitle: "Interests",
    passionsList: ["Automation", "Classical art", "Books", "Pure mathematics", "Programming and algorithms", "Sports"],
    githubTitle: "GitHub heatmap",
    projectsTitle: "Projects",
    papersTitle: "Papers",
    experienceTitle: "Experience",
    whoAmITitle: "Who Am I",
    favoriteBooksTitle: "My top 15 favourite books",
    worstBooksTitle: "Top 3 worst books",
    sportsAchievementsTitle: "Canoe sprint achievements",
    links: { live: "Live", github: "GitHub", paper: "View paper" },
  },
  es: {
    nav: { home: "Inicio", projects: "Proyectos", papers: "Papers", experience: "Experiencia", whoami: "Quien soy" },
    heroTagline: "Desarrollador de 16 anos",
    heroSub: "Enfocado en soluciones practicas que resuelven problemas reales.",
    aboutTitle: "Quien soy",
    aboutBlurb:
      "Estudiante desarrollador que estudia en Espana con pasion por las matematicas. Vive en Mallorca. Empezo a programar recientemente aprendiendo diseno web y despues paso a una programacion mas orientada a ciencia de datos.",
    languagesTitle: "Idiomas",
    languagesList: ["Hungaro (nativo)", "Ingles (fluido)", "Espanol (fluido)", "Frances (fluido)", "Catalan (aprendiendo)"],
    stackTitle: "Que uso",
    stackCoreLabel: "Nucleo",
    stackLearningLabel: "Aprendiendo",
    passionsTitle: "Intereses",
    passionsList: ["Automatizacion", "Arte clasico", "Libros", "Matematicas puras", "Programacion y algoritmos", "Deporte"],
    githubTitle: "Heatmap de GitHub",
    projectsTitle: "Proyectos",
    papersTitle: "Papers",
    experienceTitle: "Experiencia",
    whoAmITitle: "Quien soy",
    favoriteBooksTitle: "Mis 15 libros favoritos",
    worstBooksTitle: "Top 3 peores libros",
    sportsAchievementsTitle: "Logros en piraguismo de velocidad",
    links: { live: "Live", github: "GitHub", paper: "Ver paper" },
  },
  fr: {
    nav: { home: "Accueil", projects: "Projets", papers: "Papiers", experience: "Experience", whoami: "Qui je suis" },
    heroTagline: "Developpeur de 16 ans",
    heroSub: "Centre sur des solutions pratiques qui resolvent de vrais problemes.",
    aboutTitle: "Qui je suis",
    aboutBlurb:
      "Etudiant developpeur en Espagne avec une passion pour les mathematiques. Base a Majorque. A commence a programmer recemment par le design web avant de passer a une programmation plus orientee data science.",
    languagesTitle: "Langues",
    languagesList: ["Hongrois (natif)", "Anglais (courant)", "Espagnol (courant)", "Francais (courant)", "Catalan (en apprentissage)"],
    stackTitle: "Ce que j'utilise",
    stackCoreLabel: "Noyau",
    stackLearningLabel: "Apprentissage",
    passionsTitle: "Interets",
    passionsList: ["Automatisation", "Art classique", "Livres", "Mathematiques pures", "Programmation et algorithmes", "Sport"],
    githubTitle: "Heatmap GitHub",
    projectsTitle: "Projets",
    papersTitle: "Papiers",
    experienceTitle: "Experience",
    whoAmITitle: "Qui je suis",
    favoriteBooksTitle: "Mes 15 livres preferes",
    worstBooksTitle: "Top 3 pires livres",
    sportsAchievementsTitle: "Palmares en canoe sprint",
    links: { live: "Live", github: "GitHub", paper: "Voir le papier" },
  },
  de: {
    nav: { home: "Start", projects: "Projekte", papers: "Papers", experience: "Erfahrung", whoami: "Wer ich bin" },
    heroTagline: "16-jahriger Entwickler",
    heroSub: "Fokus auf praktische Losungen, die reale Probleme losen.",
    aboutTitle: "Wer ich bin",
    aboutBlurb:
      "Schuler-Entwickler in Spanien mit einer Leidenschaft fur Mathematik. Lebt auf Mallorca. Hat vor kurzem mit dem Programmieren uber Webdesign begonnen und bewegt sich jetzt starker in Richtung datenorientierter Entwicklung.",
    languagesTitle: "Sprachen",
    languagesList: ["Ungarisch (Muttersprache)", "Englisch (fliessend)", "Spanisch (fliessend)", "Franzosisch (fliessend)", "Katalanisch (lernend)"],
    stackTitle: "Was ich nutze",
    stackCoreLabel: "Kern",
    stackLearningLabel: "Lernen",
    passionsTitle: "Interessen",
    passionsList: ["Automatisierung", "Klassische Kunst", "Bucher", "Reine Mathematik", "Programmierung und Algorithmen", "Sport"],
    githubTitle: "GitHub-Heatmap",
    projectsTitle: "Projekte",
    papersTitle: "Papers",
    experienceTitle: "Erfahrung",
    whoAmITitle: "Wer ich bin",
    favoriteBooksTitle: "Meine Top 15 Lieblingsbucher",
    worstBooksTitle: "Top 3 schlechteste Bucher",
    sportsAchievementsTitle: "Erfolge im Kanusprint",
    links: { live: "Live", github: "GitHub", paper: "Papier ansehen" },
  },
  hu: {
    nav: { home: "Kezdolap", projects: "Projektek", papers: "Tanulmanyok", experience: "Tapasztalat", whoami: "Ki vagyok" },
    heroTagline: "16 eves fejleszto",
    heroSub: "Gyakorlati, valos problemakat megoldo megoldasokra fokuszalok.",
    aboutTitle: "Ki vagyok",
    aboutBlurb:
      "Spanyolorszagban tanulo diak fejleszto vagyok, eros matematikai erdeklodessel. Mallorcan elek. Nemreg kezdtem programozni webdizajnnal, majd egyre inkabb az adatorientalt fejlesztes fele fordultam.",
    languagesTitle: "Nyelvek",
    languagesList: ["Magyar (anyanyelv)", "Angol (folyekony)", "Spanyol (folyekony)", "Francia (folyekony)", "Katalan (tanulas alatt)"],
    stackTitle: "Amit hasznalok",
    stackCoreLabel: "Alap",
    stackLearningLabel: "Tanulom",
    passionsTitle: "Erdeklodes",
    passionsList: ["Automatizalas", "Klasszikus muveszet", "Konyvek", "Tiszta matematika", "Programozas es algoritmusok", "Sport"],
    githubTitle: "GitHub heatmap",
    projectsTitle: "Projektek",
    papersTitle: "Tanulmanyok",
    experienceTitle: "Tapasztalat",
    whoAmITitle: "Ki vagyok",
    favoriteBooksTitle: "A top 15 kedvenc konyvem",
    worstBooksTitle: "Top 3 legrosszabb konyv",
    sportsAchievementsTitle: "Kajak sprint eredmenyek",
    links: { live: "Elo", github: "GitHub", paper: "Tanulmany megnyitasa" },
  },
};
